### PR TITLE
revert back to JSON based cogatlas initialization

### PR DESCRIPTION
**Pull request by chrisfilo**
Updating the database from the online API is great, but it's also slow. This can impair development when you create and destroy containers often (and each time you need to run migrations). 

In production we will use the script to update the database.

### CODE REVIEW

**Comment by vsoch** [comment]
is there any reason to merge this vs. just dropping the PR? Won't the undo be the same as not doing the PR at all?

**Comment by chrisfilo** [comment]
Not at all. This only changes the migration leaving the script intact and supporting functions intact. This would allow to update cognitive atlas terms in the database from the cognitive atlas API via the script (in such case we don't care about the speed that much).

**Comment by vsoch** [comment]
ok, so we will always perform migrations / initialize with an old copy of Cognitive Atlas content, and then update with the script (API). That seems reasonable. If there is problem with the update, then what I can do is edit the script to generate an updated json file via the API.

I really want this working dynamically at some point, and possibly it's the case that we are running into trouble doing queries en-masse, and it would work better with isolated, single queries directly from the interface. 

The cogat python wrapper doesn't produce that same json anymore, but if you want an updated one it should be pretty easy for me to write a function to do that. I wouldn't even mind running the script manually whenever I do a PR to update the json, and thus keep the database updated (with a slight delay).

**Comment by chrisfilo** [comment]
I think it's fine this way until we make these queries in javascript. Just ping me each time you want the cog atlas to be updated on the production server.

**Comment by vsoch** [comment]
ok! thanks :O)

On Sun, Aug 16, 2015 at 10:16 PM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> I think it's fine this way until we make these queries in javascript. Just
> ping me each time you want the cog atlas to be updated on the production
> server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vsoch/NeuroVault/pull/8#issuecomment-131680685>.
>



-- 
Vanessa Villamia Sochat
Stanford University
(603) 321-0676

**Pull request merged**
